apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: document
  name: document
spec:
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        name: document
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - apps
      restartPolicy: Always
      containers:
      - name: document
        image: vizzuality/document
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "0.5"
            memory: "256M"
          limits:
            cpu: "1"
            memory: "512M"
        args:
          - start
        env:
          - name: PORT
            value: "4000"
          - name: NODE_ENV
            value: staging
          - name: NODE_PATH
            value: app/src
          - name: LOCAL_URL
            value: http://document.default.svc.cluster.local:4000
          - name: LOGGER_LEVEL
            value: debug
          - name: ELASTIC_URI
            valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: ELASTIC_URI
          - name: CT_URL
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_URL
          - name: CT_TOKEN
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_TOKEN
          - name: CT_REGISTER_MODE
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_REGISTER_MODE
          - name: API_VERSION
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: API_VERSION
          - name: STAMPERY_TOKEN
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: STAMPERY_TOKEN
          - name: S3_ACCESS_KEY_ID
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: DOCUMENT_S3_ACCESS_KEY_ID
          - name: S3_SECRET_ACCESS_KEY
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: DOCUMENT_S3_SECRET_ACCESS_KEY
          - name: RABBITMQ_URL
            valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: RABBITMQ_URI
        ports:
          - containerPort: 4000
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /healthcheck
            port: 4000
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 15
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /healthcheck
            port: 4000
          failureThreshold: 3
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 15
